name = "bober-vanilla+"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b83a4731855aba136b9ee7d0b2c302980856ca0f6aadb306291acdac9dece50"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["neoforge"]
