name = "bober-vanilla+"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b6254f910bb33c3344f047285f7e7462e8df04170384aa038e539a7ba1c2e58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = ["neoforge"]
